export default [
  {
    id: 1,
    name: 'Ямало-Ненецкий окружной музейно-выставочный комплекс имени И. С. Шемановского',
    shortDescription: 'Создайте новогоднее настроение себе и близким, научитесь волшебству',
    description: '<p><span>Дворец культуры Чувашского государственного университета им. И. Н. Ульянова построен в 1998 году. Является центром молодежной культуры Чувашской Республики, в котором реализуются основные молодежные проекты.</span><br /></p><p></p><p>Это современная площадка, на которой регулярно организуются и проводятся концерты, спектакли, театрализованные представления, выставки, лекции экспертов в различных областях науки, культуры и искусства, ориентированные на широкую аудиторию.<br /></p><p>Концертный зал Дворца культуры вмещает более 800 зрителей, является обладателем одной из самых больших сценических площадок г. Чебоксары.<br /></p><p>Световое и звуковое оборудование отвечает всем современным требованиям и входит в технический райдер многих звезд как российской сцены, так и западных исполнителей.<br /></p><p>В стенах дворца успешно развивается студенческое творчество, более 20 коллективов различных направлений ежегодно проводят набор в свои ряды. Педагоги-наставники не только обучают ребят вокалу, актерскому и сценическому мастерству, режиссерско-постановочному и бутафорскому искусству, чирлидингу, танцу и живописи, но и создают атмосферу настоящей творческой семьи, где ее участники поддерживают друг друга, находят новых друзей, вдохновение и открывают в себе истинные таланты.</p><p>Студии ДК ЧГУ:</p><p></p><p></p><p></p><p> </p><ul><li>вокальная сборная ЧГУ;</li><li>творческое объединение «Кафедра»;</li><li>танцевальная сборная Immortal;</li><li>сборная Чувашского государственного университета по чирлидингу – команда Power;</li><li>межвузовский студенческий театр «Абрикосовый сад»;</li><li>вокально-инструментальная студия «По-Барабану»;</li><li>Клуб веселых и находчивых;</li><li>студия звукозаписи ДК ЧГУ;</li><li>воздушная гимнастика; </li><li>студия светового и звукового сопровождения мероприятий. Техническая группа ДК ЧГУ;</li><li>«Лица университета»;</li><li>ведущие ДК ЧГУ;</li><li>молодежная республиканская платформа короткометражного кино «СтудКино».</li></ul> <p></p><p><a href="https://www.chuvsu.ru/public_html/DK/tour.html" target="_blank">Виртуальный тур</a>.</p>',
    category: {
      name: 'Дворцы культуры и клубы',
      sysName: 'dvorcy-kultury-i-kluby',
    },
    tags: [
      {
        _id: 26,
        name: 'Современное искусство',
        sysName: 'sovremennoe-iskusstvo',
      },
      {
        _id: 42,
        name: 'Культурные центры',
        sysName: 'kulturnye-centry',
      },
      {
        _id: 122,
        name: 'Искусство',
        sysName: 'iskusstvo',
      },
    ],
    workingSchedule: {
      0: {
        from: 39600000,
        to: 68400000,
      },
      1: {
        from: 39600000,
        to: 68400000,
      },
      2: {
        from: 39600000,
        to: 68400000,
      },
      3: {
        from: 39600000,
        to: 68400000,
      },
      4: {
        from: 39600000,
        to: 68400000,
      },
    },
    location: 'Салехард, ул. Чубынина, дом 38',
    address: {
      region: {
        name: 'Ямало-Ненецкий АО',
        type: 'АО',
        fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
        isPostfix: true,
      },
      city: {
        name: 'Салехард',
        type: 'г',
        fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
      },
      street: {
        name: 'Чубынина',
        type: 'ул',
        fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
        isPostfix: true,
      },
      house: {
        name: '38',
        type: 'д',
        fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
      },
    },
    mapPosition: {
      type: 'Point',
      coordinates: [
        56.132113673744676,
        47.16100709128305,
      ],
    },
    image: {
      name: '/afisha/place-1.png',
      realName: 'example.jpg',
      author: 'Юлия Яковлева',
      source: 'https://www.example.com/articles/10/22438',
    },
    gallery: [
      {
        name: 'afisha/afisha-image-1.png',
        realName: '-scKg2mKFRc.jpeg',
        author: 'Антон Мясин',
        source: 'https://vk.com/dkchgu',
      },
      {
        name: 'afisha/afisha-image-1.png',
        realName: '1.jpeg',
        author: 'Стас Дергунов',
        source: 'https://vk.com/dkchgu',
      },
    ],
    accessible: [
      'a1',
      'a2',
      'a3',
      'a4',
      'a5',
      'a7',
      'a9',
      'a10',
      'a11',
      'a12',
      'a13',
      'a15',
      'a16',
      'b3',
      'b11',
      'b12',
      'b13',
      'b14',
      'c1',
      'c2',
      'c3',
      'c5',
      'c8',
      'c7',
    ],
    needCheck: false,
    organization: {
      _id: 14562,
      name: 'Ямало-Ненецкий окружной музейно-выставочный комплекс имени И. С. Шемановского',
      locale: {
        _id: 1,
        name: 'РФ',
        sysName: 'rf',
        timezone: 'Europe/Moscow',
        isYandexExport: false,
      },
      address: {
        region: {
          name: 'Ямало-Ненецкий АО',
          type: 'АО',
          fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
          isPostfix: true,
        },
        city: {
          name: 'Салехард',
          type: 'г',
          fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
        },
        street: {
          name: 'Чубынина',
          type: 'ул',
          fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
          isPostfix: true,
        },
        house: {
          name: '38',
          type: 'д',
          fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
        },
      },
      type: 'commercial',
      inn: '7453098727',
      subordination: {
        _id: 2591,
        name: 'Челябинск',
        timezone: 'Asia/Yekaterinburg',
        sysName: 'chelyabinsk',
        isYandexExport: true,
      },
      members: [
        12354,
        69511,
        75734,
        32632,
        29296,
      ],
      localeIds: [
        2591,
        213,
        1,
      ],
      subordinationIds: [
        2591,
        213,
        1,
      ],
      roles: {},
      socialGroups: [],
      createDate: 1467983023303,
      updateDate: 1652844839301,
      postingUserId: 13798,
      support: 0,
      rating: {
        entities: 14,
        rejects: 9,
        ratio: 0.64,
        group: 'regular',
      },
      nameShort: 'Городские Зрелищные Кассы',
      category: {
        name: 'Встречи',
        sysName: 'vstrechi',
        type: 'events',
      },
      canAutoModerate: true,
      autoModerateCandidate: false,
      mastersClasses: false,
      isPushkinsCard: true,
      pushkaRulesAccepted: {
        status: true,
        user: {
          _id: 75734,
          fullName: 'Мария Шувалова',
        },
        date: 1633951489364,
      },
      isTicketsSystem: true,
      ticketsSold: 966,
      isPrivate: true,
    },
    status: 'accepted',
    updateDate: 1647593734178,
    author: {
      _id: 87994,
      fullName: 'Георгий Владимирович Чашков',
    },
    locale: {
      _id: 1,
      name: 'РФ',
      sysName: 'rf',
      timezone: 'Europe/Moscow',
      isYandexExport: false,
    },
    localeIds: [
      1882,
      174,
      1,
    ],
    createDate: 1647271081035,
    chat: {
      _id: 969514,
    },
    inAccepted: true,
    acceptDate: 1647593734288,
    externalInfo: [
      {
        updateDate: 1652432400690,
        statuses: [
          'published',
        ],
        views: 29,
        url: 'https://www.culture.ru/institutes/78669/dvorec-kultury-chuvashskogo-gosudarstvennogo-universiteta-im-i-n-ulyanova',
        createDate: 1652433053904,
        serviceName: 'Культура.рф',
        serviceUrl: 'https://www.culture.ru',
      },
    ],
    saleLink: 'string',
    isAccessibleCustom: true,
    seances: [
      {
        start: 0,
        end: 0,
        startLocal: 'string',
        endLocal: 'string',
      },
    ],
    phoneNumber: '+7 (38142) 1-01-11',
    socialLinks: [
      {
        name: 'telegram-social',
        url: 'https://t.me/zhivem_na_severe',
        title: 'Telegram',
      },
      {
        name: 'vkontakte-social',
        url: 'https://vk.com/zhivemnasevere',
        title: 'ВКонтакте',
      },
      {
        name: 'odnoklassniki-social',
        url: 'https://ok.ru/group/53447323877518',
        title: 'Одноклассники',
      },
    ],
    webLinks: [
      'arctorium.ru',
      'arc.ru',
    ],
  },
  {
    id: 2,
    name: 'Природно-этнографический комплекс п. Горнокнязевск',
    description: '<p><span>Дворец культуры Чувашского государственного университета им. И. Н. Ульянова построен в 1998 году. Является центром молодежной культуры Чувашской Республики, в котором реализуются основные молодежные проекты.</span><br /></p><p></p><p>Это современная площадка, на которой регулярно организуются и проводятся концерты, спектакли, театрализованные представления, выставки, лекции экспертов в различных областях науки, культуры и искусства, ориентированные на широкую аудиторию.<br /></p><p>Концертный зал Дворца культуры вмещает более 800 зрителей, является обладателем одной из самых больших сценических площадок г. Чебоксары.<br /></p><p>Световое и звуковое оборудование отвечает всем современным требованиям и входит в технический райдер многих звезд как российской сцены, так и западных исполнителей.<br /></p><p>В стенах дворца успешно развивается студенческое творчество, более 20 коллективов различных направлений ежегодно проводят набор в свои ряды. Педагоги-наставники не только обучают ребят вокалу, актерскому и сценическому мастерству, режиссерско-постановочному и бутафорскому искусству, чирлидингу, танцу и живописи, но и создают атмосферу настоящей творческой семьи, где ее участники поддерживают друг друга, находят новых друзей, вдохновение и открывают в себе истинные таланты.</p><p>Студии ДК ЧГУ:</p><p></p><p></p><p></p><p> </p><ul><li>вокальная сборная ЧГУ;</li><li>творческое объединение «Кафедра»;</li><li>танцевальная сборная Immortal;</li><li>сборная Чувашского государственного университета по чирлидингу – команда Power;</li><li>межвузовский студенческий театр «Абрикосовый сад»;</li><li>вокально-инструментальная студия «По-Барабану»;</li><li>Клуб веселых и находчивых;</li><li>студия звукозаписи ДК ЧГУ;</li><li>воздушная гимнастика; </li><li>студия светового и звукового сопровождения мероприятий. Техническая группа ДК ЧГУ;</li><li>«Лица университета»;</li><li>ведущие ДК ЧГУ;</li><li>молодежная республиканская платформа короткометражного кино «СтудКино».</li></ul> <p></p><p><a href="https://www.chuvsu.ru/public_html/DK/tour.html" target="_blank">Виртуальный тур</a>.</p>',
    category: {
      name: 'Дворцы культуры и клубы',
      sysName: 'dvorcy-kultury-i-kluby',
    },
    tags: [
      {
        _id: 26,
        name: 'Современное искусство',
        sysName: 'sovremennoe-iskusstvo',
      },
      {
        _id: 42,
        name: 'Культурные центры',
        sysName: 'kulturnye-centry',
      },
      {
        _id: 122,
        name: 'Искусство',
        sysName: 'iskusstvo',
      },
    ],
    workingSchedule: {
      0: {
        from: 39600000,
        to: 68400000,
      },
      1: {
        from: 39600000,
        to: 68400000,
      },
      2: {
        from: 39600000,
        to: 68400000,
      },
      3: {
        from: 39600000,
        to: 68400000,
      },
      4: {
        from: 39600000,
        to: 68400000,
      },
    },
    location: 'Горнокнязевск, ул. Северная, дом 2',
    address: {
      region: {
        name: 'Ямало-Ненецкий АО',
        type: 'АО',
        fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
        isPostfix: true,
      },
      city: {
        name: 'Горнокнязевск',
        type: 'г',
        fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
      },
      street: {
        name: 'Северная',
        type: 'ул',
        fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
        isPostfix: true,
      },
      house: {
        name: '2',
        type: 'д',
        fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
      },
    },
    mapPosition: {
      type: 'Point',
      coordinates: [
        56.132113673744676,
        47.16100709128305,
      ],
    },
    image: {
      name: '/afisha/place-2.png',
      realName: 'example.jpg',
      author: 'Юлия Яковлева',
      source: 'https://www.example.com/articles/10/22438',
    },
    gallery: [
      {
        name: '065967d22d92367584ba995b763756df.jpeg',
        realName: '-scKg2mKFRc.jpeg',
        author: 'Антон Мясин',
        source: 'https://vk.com/dkchgu',
      },
      {
        name: '1dabd60892322d4b6f0e9aacd92efe37.jpeg',
        realName: '1.jpeg',
        author: 'Стас Дергунов',
        source: 'https://vk.com/dkchgu',
      },
    ],
    accessible: [
      'a1',
      'a2',
      'a3',
      'a4',
      'a5',
      'a7',
      'a9',
      'a10',
      'a11',
      'a12',
      'a13',
      'a15',
      'a16',
      'b3',
      'b11',
      'b12',
      'b13',
      'b14',
      'c1',
      'c2',
      'c3',
      'c5',
      'c8',
      'c7',
    ],
    needCheck: false,
    organization: {
      _id: 14562,
      name: 'Ямало-Ненецкий окружной музейно-выставочный комплекс имени И. С. Шемановского',
      locale: {
        _id: 1,
        name: 'РФ',
        sysName: 'rf',
        timezone: 'Europe/Moscow',
        isYandexExport: false,
      },
      address: {
        region: {
          name: 'Ямало-Ненецкий АО',
          type: 'АО',
          fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
          isPostfix: true,
        },
        city: {
          name: 'Салехард',
          type: 'г',
          fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
        },
        street: {
          name: 'Чубынина',
          type: 'ул',
          fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
          isPostfix: true,
        },
        house: {
          name: '38',
          type: 'д',
          fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
        },
      },
      type: 'commercial',
      inn: '7453098727',
      subordination: {
        _id: 2591,
        name: 'Челябинск',
        timezone: 'Asia/Yekaterinburg',
        sysName: 'chelyabinsk',
        isYandexExport: true,
      },
      members: [
        12354,
        69511,
        75734,
        32632,
        29296,
      ],
      localeIds: [
        2591,
        213,
        1,
      ],
      subordinationIds: [
        2591,
        213,
        1,
      ],
      roles: {},
      socialGroups: [],
      createDate: 1467983023303,
      updateDate: 1652844839301,
      postingUserId: 13798,
      support: 0,
      rating: {
        entities: 14,
        rejects: 9,
        ratio: 0.64,
        group: 'regular',
      },
      nameShort: 'Городские Зрелищные Кассы',
      category: {
        name: 'Встречи',
        sysName: 'vstrechi',
        type: 'events',
      },
      canAutoModerate: true,
      autoModerateCandidate: false,
      mastersClasses: false,
      isPushkinsCard: true,
      pushkaRulesAccepted: {
        status: true,
        user: {
          _id: 75734,
          fullName: 'Мария Шувалова',
        },
        date: 1633951489364,
      },
      isTicketsSystem: true,
      ticketsSold: 966,
      isPrivate: true,
    },
    status: 'accepted',
    updateDate: 1647593734178,
    author: {
      _id: 87994,
      fullName: 'Георгий Владимирович Чашков',
    },
    locale: {
      _id: 1,
      name: 'РФ',
      sysName: 'rf',
      timezone: 'Europe/Moscow',
      isYandexExport: false,
    },
    localeIds: [
      1882,
      174,
      1,
    ],
    createDate: 1647271081035,
    chat: {
      _id: 969514,
    },
    inAccepted: true,
    acceptDate: 1647593734288,
    externalInfo: [
      {
        updateDate: 1652432400690,
        statuses: [
          'published',
        ],
        views: 29,
        url: 'https://www.culture.ru/institutes/78669/dvorec-kultury-chuvashskogo-gosudarstvennogo-universiteta-im-i-n-ulyanova',
        createDate: 1652433053904,
        serviceName: 'Культура.рф',
        serviceUrl: 'https://www.culture.ru',
      },
    ],
    saleLink: 'string',
    isAccessibleCustom: true,
    seances: [
      {
        start: 0,
        end: 0,
        startLocal: 'string',
        endLocal: 'string',
      },
    ],
  },
  {
    id: 3,
    name: 'Окружной дом ремесел на ул. Свердлова',
    description: '<p><span>Дворец культуры Чувашского государственного университета им. И. Н. Ульянова построен в 1998 году. Является центром молодежной культуры Чувашской Республики, в котором реализуются основные молодежные проекты.</span><br /></p><p></p><p>Это современная площадка, на которой регулярно организуются и проводятся концерты, спектакли, театрализованные представления, выставки, лекции экспертов в различных областях науки, культуры и искусства, ориентированные на широкую аудиторию.<br /></p><p>Концертный зал Дворца культуры вмещает более 800 зрителей, является обладателем одной из самых больших сценических площадок г. Чебоксары.<br /></p><p>Световое и звуковое оборудование отвечает всем современным требованиям и входит в технический райдер многих звезд как российской сцены, так и западных исполнителей.<br /></p><p>В стенах дворца успешно развивается студенческое творчество, более 20 коллективов различных направлений ежегодно проводят набор в свои ряды. Педагоги-наставники не только обучают ребят вокалу, актерскому и сценическому мастерству, режиссерско-постановочному и бутафорскому искусству, чирлидингу, танцу и живописи, но и создают атмосферу настоящей творческой семьи, где ее участники поддерживают друг друга, находят новых друзей, вдохновение и открывают в себе истинные таланты.</p><p>Студии ДК ЧГУ:</p><p></p><p></p><p></p><p> </p><ul><li>вокальная сборная ЧГУ;</li><li>творческое объединение «Кафедра»;</li><li>танцевальная сборная Immortal;</li><li>сборная Чувашского государственного университета по чирлидингу – команда Power;</li><li>межвузовский студенческий театр «Абрикосовый сад»;</li><li>вокально-инструментальная студия «По-Барабану»;</li><li>Клуб веселых и находчивых;</li><li>студия звукозаписи ДК ЧГУ;</li><li>воздушная гимнастика; </li><li>студия светового и звукового сопровождения мероприятий. Техническая группа ДК ЧГУ;</li><li>«Лица университета»;</li><li>ведущие ДК ЧГУ;</li><li>молодежная республиканская платформа короткометражного кино «СтудКино».</li></ul> <p></p><p><a href="https://www.chuvsu.ru/public_html/DK/tour.html" target="_blank">Виртуальный тур</a>.</p>',
    category: {
      name: 'Дворцы культуры и клубы',
      sysName: 'dvorcy-kultury-i-kluby',
    },
    tags: [
      {
        _id: 26,
        name: 'Современное искусство',
        sysName: 'sovremennoe-iskusstvo',
      },
      {
        _id: 42,
        name: 'Культурные центры',
        sysName: 'kulturnye-centry',
      },
      {
        _id: 122,
        name: 'Искусство',
        sysName: 'iskusstvo',
      },
    ],
    workingSchedule: {
      0: {
        from: 39600000,
        to: 68400000,
      },
      1: {
        from: 39600000,
        to: 68400000,
      },
      2: {
        from: 39600000,
        to: 68400000,
      },
      3: {
        from: 39600000,
        to: 68400000,
      },
      4: {
        from: 39600000,
        to: 68400000,
      },
    },
    location: 'Салехард, ул. Свердлова, дом 24',
    address: {
      region: {
        name: 'Ямало-Ненецкий АО',
        type: 'АО',
        fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
        isPostfix: true,
      },
      city: {
        name: 'Салехард',
        type: 'г',
        fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
      },
      street: {
        name: 'Свердлова',
        type: 'ул',
        fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
        isPostfix: true,
      },
      house: {
        name: '24',
        type: 'д',
        fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
      },
    },
    mapPosition: {
      type: 'Point',
      coordinates: [
        56.132113673744676,
        47.16100709128305,
      ],
    },
    image: {
      name: '/afisha/place-2.png',
      realName: 'example.jpg',
      author: 'Юлия Яковлева',
      source: 'https://www.example.com/articles/10/22438',
    },
    gallery: [
      {
        name: '065967d22d92367584ba995b763756df.jpeg',
        realName: '-scKg2mKFRc.jpeg',
        author: 'Антон Мясин',
        source: 'https://vk.com/dkchgu',
      },
      {
        name: '1dabd60892322d4b6f0e9aacd92efe37.jpeg',
        realName: '1.jpeg',
        author: 'Стас Дергунов',
        source: 'https://vk.com/dkchgu',
      },
    ],
    accessible: [
      'a1',
      'a2',
      'a3',
      'a4',
      'a5',
      'a7',
      'a9',
      'a10',
      'a11',
      'a12',
      'a13',
      'a15',
      'a16',
      'b3',
      'b11',
      'b12',
      'b13',
      'b14',
      'c1',
      'c2',
      'c3',
      'c5',
      'c8',
      'c7',
    ],
    needCheck: false,
    organization: {
      _id: 14562,
      name: 'Ямало-Ненецкий окружной музейно-выставочный комплекс имени И. С. Шемановского',
      locale: {
        _id: 1,
        name: 'РФ',
        sysName: 'rf',
        timezone: 'Europe/Moscow',
        isYandexExport: false,
      },
      address: {
        region: {
          name: 'Ямало-Ненецкий АО',
          type: 'АО',
          fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
          isPostfix: true,
        },
        city: {
          name: 'Салехард',
          type: 'г',
          fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
        },
        street: {
          name: 'Чубынина',
          type: 'ул',
          fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
          isPostfix: true,
        },
        house: {
          name: '38',
          type: 'д',
          fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
        },
      },
      type: 'commercial',
      inn: '7453098727',
      subordination: {
        _id: 2591,
        name: 'Челябинск',
        timezone: 'Asia/Yekaterinburg',
        sysName: 'chelyabinsk',
        isYandexExport: true,
      },
      members: [
        12354,
        69511,
        75734,
        32632,
        29296,
      ],
      localeIds: [
        2591,
        213,
        1,
      ],
      subordinationIds: [
        2591,
        213,
        1,
      ],
      roles: {},
      socialGroups: [],
      createDate: 1467983023303,
      updateDate: 1652844839301,
      postingUserId: 13798,
      support: 0,
      rating: {
        entities: 14,
        rejects: 9,
        ratio: 0.64,
        group: 'regular',
      },
      nameShort: 'Городские Зрелищные Кассы',
      category: {
        name: 'Встречи',
        sysName: 'vstrechi',
        type: 'events',
      },
      canAutoModerate: true,
      autoModerateCandidate: false,
      mastersClasses: false,
      isPushkinsCard: true,
      pushkaRulesAccepted: {
        status: true,
        user: {
          _id: 75734,
          fullName: 'Мария Шувалова',
        },
        date: 1633951489364,
      },
      isTicketsSystem: true,
      ticketsSold: 966,
      isPrivate: true,
    },
    status: 'accepted',
    updateDate: 1647593734178,
    author: {
      _id: 87994,
      fullName: 'Георгий Владимирович Чашков',
    },
    locale: {
      _id: 1,
      name: 'РФ',
      sysName: 'rf',
      timezone: 'Europe/Moscow',
      isYandexExport: false,
    },
    localeIds: [
      1882,
      174,
      1,
    ],
    createDate: 1647271081035,
    chat: {
      _id: 969514,
    },
    inAccepted: true,
    acceptDate: 1647593734288,
    externalInfo: [
      {
        updateDate: 1652432400690,
        statuses: [
          'published',
        ],
        views: 29,
        url: 'https://www.culture.ru/institutes/78669/dvorec-kultury-chuvashskogo-gosudarstvennogo-universiteta-im-i-n-ulyanova',
        createDate: 1652433053904,
        serviceName: 'Культура.рф',
        serviceUrl: 'https://www.culture.ru',
      },
    ],
    saleLink: 'string',
    isAccessibleCustom: true,
    seances: [
      {
        start: 0,
        end: 0,
        startLocal: 'string',
        endLocal: 'string',
      },
    ],
  },
  {
    id: 4,
    name: 'Приуральский районный краеведческий музей',
    description: '<p><span>Дворец культуры Чувашского государственного университета им. И. Н. Ульянова построен в 1998 году. Является центром молодежной культуры Чувашской Республики, в котором реализуются основные молодежные проекты.</span><br /></p><p></p><p>Это современная площадка, на которой регулярно организуются и проводятся концерты, спектакли, театрализованные представления, выставки, лекции экспертов в различных областях науки, культуры и искусства, ориентированные на широкую аудиторию.<br /></p><p>Концертный зал Дворца культуры вмещает более 800 зрителей, является обладателем одной из самых больших сценических площадок г. Чебоксары.<br /></p><p>Световое и звуковое оборудование отвечает всем современным требованиям и входит в технический райдер многих звезд как российской сцены, так и западных исполнителей.<br /></p><p>В стенах дворца успешно развивается студенческое творчество, более 20 коллективов различных направлений ежегодно проводят набор в свои ряды. Педагоги-наставники не только обучают ребят вокалу, актерскому и сценическому мастерству, режиссерско-постановочному и бутафорскому искусству, чирлидингу, танцу и живописи, но и создают атмосферу настоящей творческой семьи, где ее участники поддерживают друг друга, находят новых друзей, вдохновение и открывают в себе истинные таланты.</p><p>Студии ДК ЧГУ:</p><p></p><p></p><p></p><p> </p><ul><li>вокальная сборная ЧГУ;</li><li>творческое объединение «Кафедра»;</li><li>танцевальная сборная Immortal;</li><li>сборная Чувашского государственного университета по чирлидингу – команда Power;</li><li>межвузовский студенческий театр «Абрикосовый сад»;</li><li>вокально-инструментальная студия «По-Барабану»;</li><li>Клуб веселых и находчивых;</li><li>студия звукозаписи ДК ЧГУ;</li><li>воздушная гимнастика; </li><li>студия светового и звукового сопровождения мероприятий. Техническая группа ДК ЧГУ;</li><li>«Лица университета»;</li><li>ведущие ДК ЧГУ;</li><li>молодежная республиканская платформа короткометражного кино «СтудКино».</li></ul> <p></p><p><a href="https://www.chuvsu.ru/public_html/DK/tour.html" target="_blank">Виртуальный тур</a>.</p>',
    category: {
      name: 'Дворцы культуры и клубы',
      sysName: 'dvorcy-kultury-i-kluby',
    },
    tags: [
      {
        _id: 26,
        name: 'Современное искусство',
        sysName: 'sovremennoe-iskusstvo',
      },
      {
        _id: 42,
        name: 'Культурные центры',
        sysName: 'kulturnye-centry',
      },
      {
        _id: 122,
        name: 'Искусство',
        sysName: 'iskusstvo',
      },
    ],
    workingSchedule: {
      0: {
        from: 39600000,
        to: 68400000,
      },
      1: {
        from: 39600000,
        to: 68400000,
      },
      2: {
        from: 39600000,
        to: 68400000,
      },
      3: {
        from: 39600000,
        to: 68400000,
      },
      4: {
        from: 39600000,
        to: 68400000,
      },
    },
    location: 'Аксарка, ул. Первомайская, дом 28',
    address: {
      region: {
        name: 'Ямало-Ненецкий АО',
        type: 'АО',
        fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
        isPostfix: true,
      },
      city: {
        name: 'Аксарка',
        type: 'г',
        fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
      },
      street: {
        name: 'Первомайская',
        type: 'ул',
        fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
        isPostfix: true,
      },
      house: {
        name: '28',
        type: 'д',
        fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
      },
    },
    mapPosition: {
      type: 'Point',
      coordinates: [
        56.132113673744676,
        47.16100709128305,
      ],
    },
    image: {
      name: '/afisha/place-1.png',
      realName: 'example.jpg',
      author: 'Юлия Яковлева',
      source: 'https://www.example.com/articles/10/22438',
    },
    gallery: [
      {
        name: '065967d22d92367584ba995b763756df.jpeg',
        realName: '-scKg2mKFRc.jpeg',
        author: 'Антон Мясин',
        source: 'https://vk.com/dkchgu',
      },
      {
        name: '1dabd60892322d4b6f0e9aacd92efe37.jpeg',
        realName: '1.jpeg',
        author: 'Стас Дергунов',
        source: 'https://vk.com/dkchgu',
      },
    ],
    accessible: [
      'a1',
      'a2',
      'a3',
      'a4',
      'a5',
      'a7',
      'a9',
      'a10',
      'a11',
      'a12',
      'a13',
      'a15',
      'a16',
      'b3',
      'b11',
      'b12',
      'b13',
      'b14',
      'c1',
      'c2',
      'c3',
      'c5',
      'c8',
      'c7',
    ],
    needCheck: false,
    organization: {
      _id: 14562,
      name: 'Ямало-Ненецкий окружной музейно-выставочный комплекс имени И. С. Шемановского',
      locale: {
        _id: 1,
        name: 'РФ',
        sysName: 'rf',
        timezone: 'Europe/Moscow',
        isYandexExport: false,
      },
      address: {
        region: {
          name: 'Ямало-Ненецкий АО',
          type: 'АО',
          fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
          isPostfix: true,
        },
        city: {
          name: 'Салехард',
          type: 'г',
          fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
        },
        street: {
          name: 'Чубынина',
          type: 'ул',
          fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
          isPostfix: true,
        },
        house: {
          name: '38',
          type: 'д',
          fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
        },
      },
      type: 'commercial',
      inn: '7453098727',
      subordination: {
        _id: 2591,
        name: 'Челябинск',
        timezone: 'Asia/Yekaterinburg',
        sysName: 'chelyabinsk',
        isYandexExport: true,
      },
      members: [
        12354,
        69511,
        75734,
        32632,
        29296,
      ],
      localeIds: [
        2591,
        213,
        1,
      ],
      subordinationIds: [
        2591,
        213,
        1,
      ],
      roles: {},
      socialGroups: [],
      createDate: 1467983023303,
      updateDate: 1652844839301,
      postingUserId: 13798,
      support: 0,
      rating: {
        entities: 14,
        rejects: 9,
        ratio: 0.64,
        group: 'regular',
      },
      nameShort: 'Городские Зрелищные Кассы',
      category: {
        name: 'Встречи',
        sysName: 'vstrechi',
        type: 'events',
      },
      canAutoModerate: true,
      autoModerateCandidate: false,
      mastersClasses: false,
      isPushkinsCard: true,
      pushkaRulesAccepted: {
        status: true,
        user: {
          _id: 75734,
          fullName: 'Мария Шувалова',
        },
        date: 1633951489364,
      },
      isTicketsSystem: true,
      ticketsSold: 966,
      isPrivate: true,
    },
    status: 'accepted',
    updateDate: 1647593734178,
    author: {
      _id: 87994,
      fullName: 'Георгий Владимирович Чашков',
    },
    locale: {
      _id: 1,
      name: 'РФ',
      sysName: 'rf',
      timezone: 'Europe/Moscow',
      isYandexExport: false,
    },
    localeIds: [
      1882,
      174,
      1,
    ],
    createDate: 1647271081035,
    chat: {
      _id: 969514,
    },
    inAccepted: true,
    acceptDate: 1647593734288,
    externalInfo: [
      {
        updateDate: 1652432400690,
        statuses: [
          'published',
        ],
        views: 29,
        url: 'https://www.culture.ru/institutes/78669/dvorec-kultury-chuvashskogo-gosudarstvennogo-universiteta-im-i-n-ulyanova',
        createDate: 1652433053904,
        serviceName: 'Культура.рф',
        serviceUrl: 'https://www.culture.ru',
      },
    ],
    saleLink: 'string',
    isAccessibleCustom: true,
    seances: [
      {
        start: 0,
        end: 0,
        startLocal: 'string',
        endLocal: 'string',
      },
    ],
  },
  {
    id: 5,
    name: 'Овгортский краеведческий музей им. Елены Ильиничны Тыликовой',
    description: '<p><span>Дворец культуры Чувашского государственного университета им. И. Н. Ульянова построен в 1998 году. Является центром молодежной культуры Чувашской Республики, в котором реализуются основные молодежные проекты.</span><br /></p><p></p><p>Это современная площадка, на которой регулярно организуются и проводятся концерты, спектакли, театрализованные представления, выставки, лекции экспертов в различных областях науки, культуры и искусства, ориентированные на широкую аудиторию.<br /></p><p>Концертный зал Дворца культуры вмещает более 800 зрителей, является обладателем одной из самых больших сценических площадок г. Чебоксары.<br /></p><p>Световое и звуковое оборудование отвечает всем современным требованиям и входит в технический райдер многих звезд как российской сцены, так и западных исполнителей.<br /></p><p>В стенах дворца успешно развивается студенческое творчество, более 20 коллективов различных направлений ежегодно проводят набор в свои ряды. Педагоги-наставники не только обучают ребят вокалу, актерскому и сценическому мастерству, режиссерско-постановочному и бутафорскому искусству, чирлидингу, танцу и живописи, но и создают атмосферу настоящей творческой семьи, где ее участники поддерживают друг друга, находят новых друзей, вдохновение и открывают в себе истинные таланты.</p><p>Студии ДК ЧГУ:</p><p></p><p></p><p></p><p> </p><ul><li>вокальная сборная ЧГУ;</li><li>творческое объединение «Кафедра»;</li><li>танцевальная сборная Immortal;</li><li>сборная Чувашского государственного университета по чирлидингу – команда Power;</li><li>межвузовский студенческий театр «Абрикосовый сад»;</li><li>вокально-инструментальная студия «По-Барабану»;</li><li>Клуб веселых и находчивых;</li><li>студия звукозаписи ДК ЧГУ;</li><li>воздушная гимнастика; </li><li>студия светового и звукового сопровождения мероприятий. Техническая группа ДК ЧГУ;</li><li>«Лица университета»;</li><li>ведущие ДК ЧГУ;</li><li>молодежная республиканская платформа короткометражного кино «СтудКино».</li></ul> <p></p><p><a href="https://www.chuvsu.ru/public_html/DK/tour.html" target="_blank">Виртуальный тур</a>.</p>',
    category: {
      name: 'Дворцы культуры и клубы',
      sysName: 'dvorcy-kultury-i-kluby',
    },
    tags: [
      {
        _id: 26,
        name: 'Современное искусство',
        sysName: 'sovremennoe-iskusstvo',
      },
      {
        _id: 42,
        name: 'Культурные центры',
        sysName: 'kulturnye-centry',
      },
      {
        _id: 122,
        name: 'Искусство',
        sysName: 'iskusstvo',
      },
    ],
    workingSchedule: {
      0: {
        from: 39600000,
        to: 68400000,
      },
      1: {
        from: 39600000,
        to: 68400000,
      },
      2: {
        from: 39600000,
        to: 68400000,
      },
      3: {
        from: 39600000,
        to: 68400000,
      },
      4: {
        from: 39600000,
        to: 68400000,
      },
    },
    location: 'Овгорт, ул. Кооперативная, дом 30',
    address: {
      region: {
        name: 'Ямало-Ненецкий АО',
        type: 'АО',
        fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
        isPostfix: true,
      },
      city: {
        name: 'Овгорт',
        type: 'с',
        fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
      },
      street: {
        name: 'Кооперативная',
        type: 'ул',
        fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
        isPostfix: true,
      },
      house: {
        name: '30',
        type: 'д',
        fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
      },
    },
    mapPosition: {
      type: 'Point',
      coordinates: [
        56.132113673744676,
        47.16100709128305,
      ],
    },
    image: {
      name: '/afisha/place-1.png',
      realName: 'example.jpg',
      author: 'Юлия Яковлева',
      source: 'https://www.example.com/articles/10/22438',
    },
    gallery: [
      {
        name: '065967d22d92367584ba995b763756df.jpeg',
        realName: '-scKg2mKFRc.jpeg',
        author: 'Антон Мясин',
        source: 'https://vk.com/dkchgu',
      },
      {
        name: '1dabd60892322d4b6f0e9aacd92efe37.jpeg',
        realName: '1.jpeg',
        author: 'Стас Дергунов',
        source: 'https://vk.com/dkchgu',
      },
    ],
    accessible: [
      'a1',
      'a2',
      'a3',
      'a4',
      'a5',
      'a7',
      'a9',
      'a10',
      'a11',
      'a12',
      'a13',
      'a15',
      'a16',
      'b3',
      'b11',
      'b12',
      'b13',
      'b14',
      'c1',
      'c2',
      'c3',
      'c5',
      'c8',
      'c7',
    ],
    needCheck: false,
    organization: {
      _id: 14562,
      name: 'Ямало-Ненецкий окружной музейно-выставочный комплекс имени И. С. Шемановского',
      locale: {
        _id: 1,
        name: 'РФ',
        sysName: 'rf',
        timezone: 'Europe/Moscow',
        isYandexExport: false,
      },
      address: {
        region: {
          name: 'Ямало-Ненецкий АО',
          type: 'АО',
          fiasId: '878fc621-3708-46c7-a97f-5a13a4176b3e',
          isPostfix: true,
        },
        city: {
          name: 'Салехард',
          type: 'г',
          fiasId: 'dd8caeab-c685-4f2a-bf5f-550aca1bbc48',
        },
        street: {
          name: 'Чубынина',
          type: 'ул',
          fiasId: '9f3f6696-f195-4835-90f4-6312a5508380',
          isPostfix: true,
        },
        house: {
          name: '38',
          type: 'д',
          fiasId: '22d49dc5-8f51-4141-a405-3796cf26e0c7',
        },
      },
      type: 'commercial',
      inn: '7453098727',
      subordination: {
        _id: 2591,
        name: 'Челябинск',
        timezone: 'Asia/Yekaterinburg',
        sysName: 'chelyabinsk',
        isYandexExport: true,
      },
      members: [
        12354,
        69511,
        75734,
        32632,
        29296,
      ],
      localeIds: [
        2591,
        213,
        1,
      ],
      subordinationIds: [
        2591,
        213,
        1,
      ],
      roles: {},
      socialGroups: [],
      createDate: 1467983023303,
      updateDate: 1652844839301,
      postingUserId: 13798,
      support: 0,
      rating: {
        entities: 14,
        rejects: 9,
        ratio: 0.64,
        group: 'regular',
      },
      nameShort: 'Городские Зрелищные Кассы',
      category: {
        name: 'Встречи',
        sysName: 'vstrechi',
        type: 'events',
      },
      canAutoModerate: true,
      autoModerateCandidate: false,
      mastersClasses: false,
      isPushkinsCard: true,
      pushkaRulesAccepted: {
        status: true,
        user: {
          _id: 75734,
          fullName: 'Мария Шувалова',
        },
        date: 1633951489364,
      },
      isTicketsSystem: true,
      ticketsSold: 966,
      isPrivate: true,
    },
    status: 'accepted',
    updateDate: 1647593734178,
    author: {
      _id: 87994,
      fullName: 'Георгий Владимирович Чашков',
    },
    locale: {
      _id: 1,
      name: 'РФ',
      sysName: 'rf',
      timezone: 'Europe/Moscow',
      isYandexExport: false,
    },
    localeIds: [
      1882,
      174,
      1,
    ],
    createDate: 1647271081035,
    chat: {
      _id: 969514,
    },
    inAccepted: true,
    acceptDate: 1647593734288,
    externalInfo: [
      {
        updateDate: 1652432400690,
        statuses: [
          'published',
        ],
        views: 29,
        url: 'https://www.culture.ru/institutes/78669/dvorec-kultury-chuvashskogo-gosudarstvennogo-universiteta-im-i-n-ulyanova',
        createDate: 1652433053904,
        serviceName: 'Культура.рф',
        serviceUrl: 'https://www.culture.ru',
      },
    ],
    saleLink: 'string',
    isAccessibleCustom: true,
    seances: [
      {
        start: 0,
        end: 0,
        startLocal: 'string',
        endLocal: 'string',
      },
    ],
  },
];
